# Code Generated by Sidekick is for learning and experimentation purposes only.
# streamlit_app.py — Simple form that writes to a OneDrive-synced CSV for Excel

import os
import csv
import threading
from datetime import datetime
import streamlit as st
from pathlib import Path
import pandas as pd

# Configure a OneDrive-synced folder path via env var for portability
# Example Windows: setx DATA_DIR "C:\\Users\\you\\OneDrive - OrgName\\form-data"
# Example macOS: export DATA_DIR="$HOME/Library/CloudStorage/OneDrive-OrgName/form-data"
DATA_DIR = Path(os.environ.get("DATA_DIR", Path(__file__).resolve().parent / "data"))
CSV_PATH = DATA_DIR / "submissions.csv"
COLUMNS = ["FullName", "Email", "Lansing", "SubmittedAt"]

# Hidden mirror file (same directory; name starts with a dot)
RECENT_FILE = DATA_DIR / ".recent_submissions.csv"

DATA_DIR.mkdir(parents=True, exist_ok=True)
_write_lock = threading.Lock()

def append_row(row_dict):
    with _write_lock:
        is_new = (not CSV_PATH.exists()) or CSV_PATH.stat().st_size == 0
        with CSV_PATH.open("a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            if is_new:
                w.writeheader()
            w.writerow({k: row_dict.get(k, "") for k in COLUMNS})

def append_recent_row(row_dict):
    with _write_lock:
        is_new = (not RECENT_FILE.exists()) or RECENT_FILE.stat().st_size == 0
        with RECENT_FILE.open("a", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLUMNS)
            if is_new:
                w.writeheader()
            w.writerow({k: row_dict.get(k, "") for k in COLUMNS})

st.set_page_config(page_title="GenAI Session Sign-Up", page_icon="📝", layout="centered")
st.title("GenAI Session Sign-Up")
st.write("Interested in attending the GenAI in Action: GenAI 101 learning session? Sign up below!")

with st.form("signup", clear_on_submit=True):
    full_name = st.text_input("Full name", placeholder="Jane Doe")
    email = st.text_input("Email", placeholder="jane@example.com")
    lansing_choice = st.radio(
        "Will you be co-locating in the Lansing Office on February 3?",
        options=["Yes", "No"],
        horizontal=True
    )
    submitted = st.form_submit_button("Submit")

if submitted:
    # Minimal validation
    if not full_name.strip():
        st.error("Full name is required.")
        st.stop()
    if "@" not in email or "." not in email:
        st.error("Please provide a valid email address.")
        st.stop()

    row = {
        "FullName": full_name.strip(),
        "Email": email.strip(),
        "Lansing": lansing_choice,  # "Yes" or "No" from the radio
        "SubmittedAt": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
    }

    try:
        append_row(row)
        append_recent_row(row)  # mirror append to hidden file
        st.success("Thank you! Your submission has been recorded.")
    except Exception as e:
        st.error(f"Could not save your submission: {e}")

st.divider()
st.subheader("Recent submissions")

if os.path.exists(CSV_PATH):
    try:
        with open(CSV_PATH, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        if rows:
            st.dataframe(rows[-10:], use_container_width=True)
        else:
            st.info("No submissions yet.")
    except Exception as e:
        st.warning(f"Unable to load preview: {e}")
else:
    st.info("No submissions yet.")

# If you want column/row editing tools, uncomment pandas import above and this block:
    if os.path.exists(CSV_PATH):
        try:
            df = pd.read_csv(CSV_PATH)
        except Exception as e:
            st.error(f"Unable to load CSV for admin tools: {e}")
            df = None
    
        if df is not None:
            st.markdown("**Remove selected columns**")
            drop_cols = st.multiselect("Columns to remove", options=list(df.columns))
            if st.button("Remove columns"):
                try:
                    df2 = df.drop(columns=drop_cols, errors="ignore")
                    df2.to_csv(CSV_PATH, index=False, encoding="utf-8")
                    st.success(f"Removed columns: {', '.join(drop_cols)}")
                except Exception as e:
                    st.error(f"Error removing columns: {e}")
    
            st.divider()
    
            st.markdown("**Delete rows by Email (exact match)**")
            email_to_delete = st.text_input("Email to delete")
            if st.button("Delete rows"):
                try:
                    before = len(df)
                    df2 = df[df["Email"] != email_to_delete] if email_to_delete else df
                    df2.to_csv(CSV_PATH, index=False, encoding="utf-8")
                    st.success(f"Deleted {before - len(df2)} rows for: {email_to_delete}")
                except Exception as e:
                    st.error(f"Error deleting rows: {e}")
    
            st.divider()
    
            st.markdown("**Rename a column**")
            old = st.selectbox("Current column", options=list(df.columns))
            new = st.text_input("New name", value=old)
            if st.button("Rename column"):
                try:
                    df3 = df.rename(columns={old: new})
                    df3.to_csv(CSV_PATH, index=False, encoding="utf-8")
                    st.success(f"Renamed {old} to {new}")
                except Exception as e:
                    st.error(f"Error renaming column: {e}")

